/*
 * SmartBearCoin - Payees API
 *
 * The **Customer Management - Payees API** - allows retrieval of payees and payee transactions. The Payees API allows consumers to search, identify and retrieve payee information in one specified country. Customer centricity is part of the DNA of SmartBearCoin. Therefore, Customer Management (CM) is considered a core business capability. The focus of CM is outward focused on enabling a consistent, digital customer experience, throughout the customer journey and across channels (omnichannel). This leads to measurable improvements of customer satisfaction and the increase of sales volume and/or margin. Value exposed through Customer Management capabilities is build upon an API-First strategy at SmartBearCoin. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: customer.management.apiteam@smartbearcoin.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace SmartBearCoin.CustomerManagement.Models.OpenAPI
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PaginationLinks : IEquatable<PaginationLinks>
    { 
        /// <summary>
        /// The canonical URL for the current page
        /// </summary>
        /// <value>The canonical URL for the current page</value>
        [Required]

        [DataMember(Name="self")]
        public string Self { get; set; } = string.Empty;

        /// <summary>
        /// The canonical URL for the next page, if available
        /// </summary>
        /// <value>The canonical URL for the next page, if available</value>

        [DataMember(Name="next")]
        public string? Next { get; set; }

        /// <summary>
        /// The canonical URL for the previous page, if available
        /// </summary>
        /// <value>The canonical URL for the previous page, if available</value>

        [DataMember(Name="previous")]
        public string? Previous { get; set; }

        /// <summary>
        /// The canonical URL for the last page
        /// </summary>
        /// <value>The canonical URL for the last page</value>
        [Required]

        [DataMember(Name="last")]
        public string Last { get; set; } = string.Empty;

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaginationLinks {\n");
            sb.Append("  Self: ").Append(Self).Append("\n");
            sb.Append("  Next: ").Append(Next).Append("\n");
            sb.Append("  Previous: ").Append(Previous).Append("\n");
            sb.Append("  Last: ").Append(Last).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object? obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaginationLinks)obj);
        }

        /// <summary>
        /// Returns true if PaginationLinks instances are equal
        /// </summary>
        /// <param name="other">Instance of PaginationLinks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaginationLinks? other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Self == other?.Self ||
                    Self != null &&
                    Self.Equals(other?.Self)
                ) && 
                (
                    Next == other?.Next ||
                    Next != null &&
                    Next.Equals(other?.Next)
                ) && 
                (
                    Previous == other?.Previous ||
                    Previous != null &&
                    Previous.Equals(other?.Previous)
                ) && 
                (
                    Last == other?.Last ||
                    Last != null &&
                    Last.Equals(other?.Last)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Self != null)
                    hashCode = hashCode * 59 + Self.GetHashCode();
                    if (Next != null)
                    hashCode = hashCode * 59 + Next.GetHashCode();
                    if (Previous != null)
                    hashCode = hashCode * 59 + Previous.GetHashCode();
                    if (Last != null)
                    hashCode = hashCode * 59 + Last.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaginationLinks left, PaginationLinks right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaginationLinks left, PaginationLinks right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
