/*
 * SmartBearCoin - Payees API
 *
 * The **Customer Managment - Payees API** - allows retrieval of payees and payee transactions. The Payees API allows consumers to search, identify and retrieve payee information in one specified country. Customer centricity is part of the DNA of SmartBearCoin. Therefore, Customer Management (CM) is considered a core business capability. The focus of CM is outward focused on enabling a consistent, digital customer experience, throughout the customer journey and across channels (omnichannel). This leads to measurable improvements of customer satisfaction and the increase of sales volume and/or margin. Value exposed through Customer Management capabilities is build upon an API-First strategy at SmartBearCoin. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: customer.management.apiteam@smartbearcoin.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace SmartBearCoin.CustomerManagement.Models.OpenAPI
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProblemDetails : IEquatable<ProblemDetails>
    { 
        /// <summary>
        /// A URI reference that identifies the problem type.
        /// </summary>
        /// <value>A URI reference that identifies the problem type.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum MissingRequestHeaderEnum for https://api.smartbearcoin.com/problems/missing-request-header
            /// </summary>
            [EnumMember(Value = "https://api.smartbearcoin.com/problems/missing-request-header")]
            MissingRequestHeaderEnum = 0,
            /// <summary>
            /// Enum MissingRequestParameterEnum for https://api.smartbearcoin.com/problems/missing-request-parameter
            /// </summary>
            [EnumMember(Value = "https://api.smartbearcoin.com/problems/missing-request-parameter")]
            MissingRequestParameterEnum = 1,
            /// <summary>
            /// Enum InvalidRequestHeaderFormatEnum for https://api.smartbearcoin.com/problems/invalid-request-header-format
            /// </summary>
            [EnumMember(Value = "https://api.smartbearcoin.com/problems/invalid-request-header-format")]
            InvalidRequestHeaderFormatEnum = 2,
            /// <summary>
            /// Enum InvalidRequestParameterFormatEnum for https://api.smartbearcoin.com/problems/invalid-request-parameter-format
            /// </summary>
            [EnumMember(Value = "https://api.smartbearcoin.com/problems/invalid-request-parameter-format")]
            InvalidRequestParameterFormatEnum = 3,
            /// <summary>
            /// Enum InvalidRequestParameterValueEnum for https://api.smartbearcoin.com/problems/invalid-request-parameter-value
            /// </summary>
            [EnumMember(Value = "https://api.smartbearcoin.com/problems/invalid-request-parameter-value")]
            InvalidRequestParameterValueEnum = 4,
            /// <summary>
            /// Enum InternalServerErrorEnum for https://api.smartbearcoin.com/problems/internal-server-error
            /// </summary>
            [EnumMember(Value = "https://api.smartbearcoin.com/problems/internal-server-error")]
            InternalServerErrorEnum = 5        }

        /// <summary>
        /// A URI reference that identifies the problem type.
        /// </summary>
        /// <value>A URI reference that identifies the problem type.</value>
        [Required]

        [DataMember(Name="type")]
        public TypeEnum? Type { get; set; }

        /// <summary>
        /// a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization
        /// </summary>
        /// <value>a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TitleEnum
        {
            /// <summary>
            /// Enum MissingRequestHeaderEnum for missing-request-header
            /// </summary>
            [EnumMember(Value = "missing-request-header")]
            MissingRequestHeaderEnum = 0,
            /// <summary>
            /// Enum MissingRequestParameterEnum for missing-request-parameter
            /// </summary>
            [EnumMember(Value = "missing-request-parameter")]
            MissingRequestParameterEnum = 1,
            /// <summary>
            /// Enum InvalidRequestHeaderFormatEnum for invalid-request-header-format
            /// </summary>
            [EnumMember(Value = "invalid-request-header-format")]
            InvalidRequestHeaderFormatEnum = 2,
            /// <summary>
            /// Enum InvalidRequestParameterFormatEnum for invalid-request-parameter-format
            /// </summary>
            [EnumMember(Value = "invalid-request-parameter-format")]
            InvalidRequestParameterFormatEnum = 3,
            /// <summary>
            /// Enum InvalidRequestParameterValueEnum for invalid-request-parameter-value
            /// </summary>
            [EnumMember(Value = "invalid-request-parameter-value")]
            InvalidRequestParameterValueEnum = 4,
            /// <summary>
            /// Enum InternalServerErrorEnum for internal-server-error
            /// </summary>
            [EnumMember(Value = "internal-server-error")]
            InternalServerErrorEnum = 5        }

        /// <summary>
        /// a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization
        /// </summary>
        /// <value>a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization</value>
        [Required]

        [DataMember(Name="title")]
        public TitleEnum? Title { get; set; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem. Like title, this field value can be localized.
        /// </summary>
        /// <value>A human-readable explanation specific to this occurrence of the problem. Like title, this field value can be localized.</value>
        [Required]

        [DataMember(Name="detail")]
        public string Detail { get; set; }

        /// <summary>
        /// Gets or Sets ContextData
        /// </summary>

        [DataMember(Name="contextData")]
        public List<ProblemContextData> ContextData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProblemDetails {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Detail: ").Append(Detail).Append("\n");
            sb.Append("  ContextData: ").Append(ContextData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProblemDetails)obj);
        }

        /// <summary>
        /// Returns true if ProblemDetails instances are equal
        /// </summary>
        /// <param name="other">Instance of ProblemDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProblemDetails other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) && 
                (
                    Title == other.Title ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) && 
                (
                    Detail == other.Detail ||
                    Detail != null &&
                    Detail.Equals(other.Detail)
                ) && 
                (
                    ContextData == other.ContextData ||
                    ContextData != null &&
                    ContextData.SequenceEqual(other.ContextData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                    if (Detail != null)
                    hashCode = hashCode * 59 + Detail.GetHashCode();
                    if (ContextData != null)
                    hashCode = hashCode * 59 + ContextData.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProblemDetails left, ProblemDetails right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProblemDetails left, ProblemDetails right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
